#!/bin/bash

# Exit the script with an error message if PYFILE is not set or is an empty string
[ -z "$PYFILE" ] && { echo "Error: PYFILE environment variable is not set."; exit 1; }
# Run the Python script
python3 $PYFILE
